import React, { useState, useEffect } from 'react';
import {
  Building2,
  Tag,
  Phone,
  Mail,
  MapPin,
  Copy,
  Plus,
  Save,
  Sparkles,
  CheckCircle2,
  ShieldCheck,
} from 'lucide-react';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Button } from '@/components/ui/button';
import { Spinner } from '@/components/ui/spinner';
import { AddressForm, type NigerianAddress } from '@/components/location/AddressForm';
import { useOrgAddressPrefill } from '@/hooks/useOrgAddressPrefill';
import { OtpVerificationModal } from '@/components/phone/OtpVerificationModal';
import { api } from '@/lib/api';
import { toast } from 'sonner';
import {
  type BranchFormData,
  type BranchFormErrors,
  cleanPhone,
  formatPhoneE164,
  assembleAddress,
  generateBranchCode,
  validateBranchForm,
} from './branchFormUtils';

export interface BranchFormProps {
  mode?: 'create' | 'edit';
  initialValues?: Partial<BranchFormData>;
  organizationId?: string;
  branchId?: string;
  showCode?: boolean;
  showEmail?: boolean;
  showPrimaryCheckbox?: boolean;
  isPrimaryDisabled?: boolean;
  isPrimaryDefault?: boolean;
  showOrgPrefill?: boolean;
  isLimitReached?: boolean;
  limitTooltip?: string;
  limitBannerMessage?: string;
  isSubmitting?: boolean;
  submitLabel?: string;
  submittingLabel?: string;
  secondarySubmitLabel?: string;
  onSecondarySubmit?: (data: BranchFormData) => Promise<void> | void;
  onSubmit: (data: BranchFormData) => Promise<void> | void;
  onCancel?: () => void;
  theme?: 'plum' | 'indigo';
  variant?: 'card' | 'plain';
  className?: string;
}

export const BranchForm: React.FC<BranchFormProps> = ({
  mode = 'create',
  initialValues,
  organizationId,
  branchId,
  showCode = true,
  showEmail = false,
  showPrimaryCheckbox = false,
  isPrimaryDisabled = false,
  isPrimaryDefault = false,
  showOrgPrefill = true,
  isLimitReached = false,
  limitTooltip,
  limitBannerMessage,
  isSubmitting = false,
  submitLabel,
  submittingLabel,
  secondarySubmitLabel,
  onSecondarySubmit,
  onSubmit,
  onCancel,
  theme = 'plum',
  variant = 'card',
  className = '',
}) => {
  const { prefill: prefillFromOrg, isLoading: isPrefilling } = useOrgAddressPrefill(organizationId);

  // Form states
  const [name, setName] = useState(initialValues?.name || '');
  const [code, setCode] = useState(initialValues?.code || '');
  const [isCodeManuallyEdited, setIsCodeManuallyEdited] = useState(Boolean(initialValues?.code));
  const [isCodeAutoGenerated, setIsCodeAutoGenerated] = useState(false);
  const [phoneDigits, setPhoneDigits] = useState(
    initialValues?.phoneDigits || (initialValues?.phone ? cleanPhone(initialValues.phone) : '')
  );
  const [phoneVerified, setPhoneVerified] = useState(initialValues?.phoneVerified ?? false);
  const [isPhoneVerifyModalOpen, setIsPhoneVerifyModalOpen] = useState(false);
  const [isStartingPhoneVerify, setIsStartingPhoneVerify] = useState(false);

  const [email, setEmail] = useState(initialValues?.email || '');
  const [street, setStreet] = useState(initialValues?.street || '');
  const [city, setCity] = useState(initialValues?.city || '');
  const [stateName, setStateName] = useState(initialValues?.state || 'Lagos');
  const [stateCode, setStateCode] = useState(initialValues?.stateCode || 'LA');
  const [lga, setLga] = useState(initialValues?.lga || '');
  const [blockNumber, setBlockNumber] = useState(initialValues?.blockNumber || '');
  const [area, setArea] = useState(initialValues?.area || '');
  const [landmark, setLandmark] = useState(initialValues?.landmark || '');
  const [postalCode, setPostalCode] = useState(initialValues?.postalCode || '');
  const [isPrimary, setIsPrimary] = useState(initialValues?.isPrimary ?? isPrimaryDefault);
  const [errors, setErrors] = useState<BranchFormErrors>({});

  const country = initialValues?.country || 'Nigeria';

  // Synchronize when initialValues change (e.g. edit mode loads data)
  useEffect(() => {
    if (initialValues) {
      if (initialValues.name !== undefined) setName(initialValues.name);
      if (initialValues.code !== undefined) {
        setCode(initialValues.code);
        if (initialValues.code) {
          setIsCodeManuallyEdited(true);
          setIsCodeAutoGenerated(false);
        }
      }
      if (initialValues.phoneDigits !== undefined) {
        setPhoneDigits(initialValues.phoneDigits);
      } else if (initialValues.phone !== undefined) {
        setPhoneDigits(cleanPhone(initialValues.phone));
      }
      if (initialValues.phoneVerified !== undefined) setPhoneVerified(initialValues.phoneVerified);
      if (initialValues.email !== undefined) setEmail(initialValues.email);
      if (initialValues.street !== undefined) setStreet(initialValues.street);
      if (initialValues.city !== undefined) setCity(initialValues.city);
      if (initialValues.state !== undefined) setStateName(initialValues.state || 'Lagos');
      if (initialValues.stateCode !== undefined) setStateCode(initialValues.stateCode || '');
      if (initialValues.lga !== undefined) setLga(initialValues.lga || '');
      if (initialValues.blockNumber !== undefined) setBlockNumber(initialValues.blockNumber || '');
      if (initialValues.area !== undefined) setArea(initialValues.area || '');
      if (initialValues.landmark !== undefined) setLandmark(initialValues.landmark || '');
      if (initialValues.postalCode !== undefined) setPostalCode(initialValues.postalCode || '');
      if (initialValues.isPrimary !== undefined) setIsPrimary(initialValues.isPrimary);
    }
  }, [initialValues]);

  const handlePrefill = () => {
    prefillFromOrg({
      setStreet,
      setCity,
      setStateName,
      setPhoneDigits: (digits) => {
        setPhoneDigits(cleanPhone(digits));
        setPhoneVerified(false);
      },
    });
  };

  const getFormData = (): BranchFormData => {
    const formattedPhone = formatPhoneE164(phoneDigits);
    const address = assembleAddress({ blockNumber, street, area, city, lga, state: stateName, country });

    return {
      name: name.trim(),
      code: showCode ? (code.trim().toUpperCase() || generateBranchCode(name.trim())) : undefined,
      phoneDigits: cleanPhone(phoneDigits),
      phone: formattedPhone,
      phoneVerified,
      email: showEmail && email.trim() ? email.trim() : undefined,
      street: street.trim() || undefined,
      city: city.trim() || undefined,
      state: stateName.trim() || undefined,
      stateCode: stateCode || undefined,
      lga: lga.trim() || undefined,
      blockNumber: blockNumber.trim() || undefined,
      area: area.trim() || undefined,
      landmark: landmark.trim() || undefined,
      postalCode: postalCode.trim() || undefined,
      country,
      address,
      isPrimary,
    };
  };

  const validate = (): boolean => {
    const data = getFormData();
    const validationErrors = validateBranchForm(data);
    setErrors(validationErrors);

    if (validationErrors.name) {
      toast.error(validationErrors.name);
      return false;
    }
    if (validationErrors.email) {
      toast.error(validationErrors.email);
      return false;
    }
    if (validationErrors.phoneDigits) {
      toast.error(validationErrors.phoneDigits);
      return false;
    }
    return true;
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (isLimitReached) {
      toast.error(limitTooltip || 'Branch limit reached. Please upgrade your plan.');
      return;
    }
    if (!validate()) return;
    await onSubmit(getFormData());
  };

  const handleSecondarySubmit = async () => {
    if (isLimitReached) {
      toast.error(limitTooltip || 'Branch limit reached. Please upgrade your plan.');
      return;
    }
    if (!validate()) return;
    if (onSecondarySubmit) {
      await onSecondarySubmit(getFormData());
    }
  };

  // Phone Verification Start
  const handleStartPhoneVerification = async () => {
    const cleaned = cleanPhone(phoneDigits);
    if (!cleaned || cleaned.length < 10) {
      toast.error('Please enter a valid 10 or 11 digit Nigerian phone number first.');
      return;
    }

    const formattedPhone = formatPhoneE164(phoneDigits);
    if (!formattedPhone) return;

    setIsStartingPhoneVerify(true);
    try {
      const activeOrg = organizationId || 'current';
      if (branchId) {
        await api.post(`/organizations/${activeOrg}/branches/${branchId}/phone/verification/start`, {
          phone: formattedPhone,
          purpose: 'branch_phone_verification',
        });
      } else {
        await api.post(`/organizations/${activeOrg}/settings/phone/verification/start`, {
          phone: formattedPhone,
          purpose: 'branch_phone_verification',
        });
      }
      setIsPhoneVerifyModalOpen(true);
      toast.success(`Verification code sent to ${formattedPhone}`);
    } catch (err: any) {
      toast.error(err?.message || 'Failed to start phone verification. Please check the number.');
    } finally {
      setIsStartingPhoneVerify(false);
    }
  };

  const handleVerifyOtp = async (otp: string) => {
    const activeOrg = organizationId || 'current';
    if (branchId) {
      await api.post(`/organizations/${activeOrg}/branches/${branchId}/phone/verification/verify`, {
        code: otp.trim(),
        purpose: 'branch_phone_verification',
      });
    } else {
      await api.post(`/organizations/${activeOrg}/settings/phone/verification/verify`, {
        code: otp.trim(),
        purpose: 'branch_phone_verification',
      });
    }
    setPhoneVerified(true);
    toast.success('Branch phone verified successfully!');
  };

  const handleResendOtp = async () => {
    const activeOrg = organizationId || 'current';
    if (branchId) {
      await api.post(`/organizations/${activeOrg}/branches/${branchId}/phone/verification/resend`, {
        purpose: 'branch_phone_verification',
      });
    } else {
      await api.post(`/organizations/${activeOrg}/settings/phone/verification/resend`, {
        purpose: 'branch_phone_verification',
      });
    }
    toast.success('Verification code resent.');
  };

  // Styling based on theme
  const isIndigo = theme === 'indigo';
  const containerClasses =
    variant === 'card'
      ? isIndigo
        ? 'p-5 rounded-2xl border border-indigo-500/20 bg-indigo-500/5 space-y-4'
        : 'p-5 sm:p-6 rounded-2xl bg-[#160f14]/80 border border-white/10 space-y-4'
      : 'space-y-4';

  const brandAccentBg = isIndigo
    ? 'bg-indigo-600 hover:bg-indigo-500 text-white'
    : 'bg-[#714b67] hover:bg-[#86597a] text-white shadow-lg shadow-[#714b67]/20';

  const brandFocusRing = isIndigo
    ? 'focus-within:ring-1 focus-within:ring-indigo-500 focus-within:border-indigo-500'
    : 'focus-within:ring-1 focus-within:ring-[#714b67] focus-within:border-[#714b67]';

  const inputBg = isIndigo ? 'bg-black/30 border-white/10' : 'bg-black/60 border-white/15';

  const defaultSubmitText =
    submitLabel || (mode === 'edit' ? 'Save Changes' : 'Create Branch');
  const defaultSubmittingText =
    submittingLabel || (mode === 'edit' ? 'Saving...' : 'Creating...');

  const cleanedPhoneDigits = cleanPhone(phoneDigits);
  const canVerifyPhone = cleanedPhoneDigits.length >= 10;

  return (
    <>
      <form onSubmit={handleSubmit} className={`${containerClasses} ${className}`}>
        {/* Header bar when in card variant or cancel is available */}
        <div className="flex items-center justify-between">
          <h3 className="text-sm font-bold text-white flex items-center gap-2">
            {mode === 'edit' ? (
              <Save className={`w-4 h-4 ${isIndigo ? 'text-indigo-400' : 'text-[#d4a8c9]'}`} />
            ) : (
              <Plus className={`w-4 h-4 ${isIndigo ? 'text-indigo-400' : 'text-[#d4a8c9]'}`} />
            )}
            <span>{mode === 'edit' ? 'Edit Branch Details' : 'New Branch'}</span>
          </h3>

          <div className="flex items-center gap-2">
            {showOrgPrefill && (
              <button
                type="button"
                onClick={handlePrefill}
                disabled={isPrefilling}
                className={`inline-flex items-center gap-1.5 px-2.5 py-1 rounded-lg text-xs font-semibold transition cursor-pointer disabled:opacity-50 ${
                  isIndigo
                    ? 'bg-indigo-500/10 hover:bg-indigo-500/20 border border-indigo-500/30 text-indigo-300'
                    : 'bg-[#714b67]/20 hover:bg-[#714b67]/40 border border-[#714b67]/40 text-[#d4a8c9]'
                }`}
              >
                <Copy className="w-3 h-3" />
                <span>{isPrefilling ? 'Loading Org Address...' : 'Use Org Address & Phone'}</span>
              </button>
            )}

            {onCancel && (
              <button
                type="button"
                onClick={onCancel}
                className="text-xs text-slate-500 hover:text-slate-300 transition-colors cursor-pointer px-1 py-0.5"
              >
                Cancel
              </button>
            )}
          </div>
        </div>

        {/* Name and Code row */}
        <div className={`grid grid-cols-1 ${showCode ? 'sm:grid-cols-3' : ''} gap-3`}>
          <div className={`${showCode ? 'sm:col-span-2' : ''} space-y-1.5`}>
            <Label className="text-xs text-slate-300 font-medium">
              Branch Name <span className="text-rose-400">*</span>
            </Label>
            <div className="relative">
              <Building2 className="w-3.5 h-3.5 text-slate-500 absolute left-3 top-1/2 -translate-y-1/2" />
              <Input
                value={name}
                onChange={(e) => {
                  setName(e.target.value);
                  if (showCode && !isCodeManuallyEdited && mode === 'create') {
                    const generated = generateBranchCode(e.target.value);
                    setCode(generated);
                    setIsCodeAutoGenerated(Boolean(generated));
                  }
                }}
                onBlur={() => {
                  if (showCode && !isCodeManuallyEdited && name.trim()) {
                    const generated = generateBranchCode(name.trim());
                    if (generated) {
                      setCode(generated);
                      setIsCodeAutoGenerated(true);
                    }
                  }
                }}
                placeholder="e.g. Marina Main Store, Ikeja Outlet"
                className={`pl-9 h-9 text-xs text-white rounded-md ${inputBg}`}
                required
              />
            </div>
            {errors.name && <p className="text-[11px] text-rose-400">{errors.name}</p>}
          </div>

          {showCode && (
            <div className="space-y-1.5">
              <div className="flex items-center justify-between">
                <Label className="text-xs text-slate-300 font-medium">Branch Code</Label>
                {isCodeAutoGenerated && code && (
                  <span
                    className="text-[10px] font-mono px-1.5 py-0.2 rounded bg-indigo-500/10 text-indigo-300 border border-indigo-500/20 select-none"
                    title="Auto-generated from branch name. You can manually edit this code."
                  >
                    Auto
                  </span>
                )}
              </div>
              <div className="relative">
                <Tag className="w-3.5 h-3.5 text-slate-500 absolute left-3 top-1/2 -translate-y-1/2" />
                <Input
                  value={code}
                  onChange={(e) => {
                    setIsCodeManuallyEdited(true);
                    setIsCodeAutoGenerated(false);
                    setCode(
                      e.target.value
                        .toUpperCase()
                        .replace(/[^A-Z0-9]/g, '')
                        .slice(0, 6)
                    );
                  }}
                  placeholder="e.g. MAR"
                  maxLength={6}
                  className={`pl-9 h-9 text-xs text-white font-mono uppercase rounded-md ${inputBg}`}
                />
              </div>
            </div>
          )}
        </div>

        {/* Phone and Email row */}
        <div className={`grid grid-cols-1 ${showEmail ? 'sm:grid-cols-2' : 'sm:grid-cols-2'} gap-3`}>
          <div className="space-y-1.5">
            <div className="flex items-center justify-between">
              <Label className="text-xs text-slate-300 font-medium">Branch Phone</Label>
              {phoneVerified && (
                <span className="inline-flex items-center gap-1 text-[10px] font-semibold text-emerald-400">
                  <CheckCircle2 className="w-3 h-3" /> Verified
                </span>
              )}
            </div>

            <div
              className={`relative flex items-center h-9 ${inputBg} rounded-md text-xs transition-all ${brandFocusRing}`}
            >
              <div className="flex items-center gap-1.5 pl-3 pr-2.5 h-full border-r border-white/10 text-slate-300 select-none shrink-0 bg-white/[0.02]">
                <Phone className="w-3 h-3 text-slate-500" />
                <span className="text-xs font-medium text-slate-200">+234</span>
              </div>
              <input
                type="tel"
                placeholder="801 234 5678"
                value={phoneDigits}
                onChange={(e) => {
                  setPhoneDigits(cleanPhone(e.target.value));
                  setPhoneVerified(false);
                }}
                className="w-full h-full bg-transparent px-3 text-white placeholder:text-slate-600 text-xs focus:outline-none"
              />

              {/* Verify Button or Verified Badge inside input container */}
              {canVerifyPhone && (
                <div className="pr-1.5 shrink-0">
                  {phoneVerified ? (
                    <span
                      className="inline-flex items-center gap-1 px-2 py-0.5 rounded text-[10px] font-semibold bg-emerald-500/15 text-emerald-300 border border-emerald-500/30"
                      title="Branch phone is verified"
                    >
                      <CheckCircle2 className="w-3 h-3 text-emerald-400" />
                      <span>Verified</span>
                    </span>
                  ) : (
                    <button
                      type="button"
                      onClick={handleStartPhoneVerification}
                      disabled={isStartingPhoneVerify}
                      className={`inline-flex items-center gap-1 px-2 py-0.5 rounded text-[10px] font-semibold transition cursor-pointer disabled:opacity-50 ${
                        isIndigo
                          ? 'bg-indigo-500/20 hover:bg-indigo-500/30 text-indigo-300 border border-indigo-500/30'
                          : 'bg-[#714b67]/30 hover:bg-[#714b67]/50 text-[#f0d8e8] border border-[#714b67]/40'
                      }`}
                      title="Verify phone via SMS (optional)"
                    >
                      {isStartingPhoneVerify ? (
                        <Spinner size="sm" />
                      ) : (
                        <ShieldCheck className="w-3 h-3" />
                      )}
                      <span>Verify</span>
                    </button>
                  )}
                </div>
              )}
            </div>
            {errors.phoneDigits && (
              <p className="text-[11px] text-rose-400">{errors.phoneDigits}</p>
            )}
          </div>

          {showEmail && (
            <div className="space-y-1.5">
              <Label className="text-xs text-slate-300 font-medium">Branch Email (Optional)</Label>
              <div className="relative">
                <Mail className="w-3.5 h-3.5 text-slate-500 absolute left-3 top-1/2 -translate-y-1/2" />
                <Input
                  type="email"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  placeholder="branch@company.com"
                  className={`pl-9 h-9 text-xs text-white rounded-md ${inputBg}`}
                />
              </div>
              {errors.email && <p className="text-[11px] text-rose-400">{errors.email}</p>}
            </div>
          )}
        </div>

        {/* Physical Location & Address */}
        <div className="space-y-3 pt-2 border-t border-white/10">
          <div className="flex items-center gap-1.5 text-xs font-semibold text-slate-300">
            <MapPin className={`w-3.5 h-3.5 ${isIndigo ? 'text-indigo-400' : 'text-[#d4a8c9]'}`} />
            <span>Physical Location & Address</span>
          </div>

          <AddressForm
            countryFixed
            value={{ country, state: stateName, stateCode, lga, city, street, blockNumber, area, landmark, postalCode }}
            onChange={(next: NigerianAddress) => {
              setStateName(next.state);
              setStateCode(next.stateCode || '');
              setLga(next.lga);
              setCity(next.city);
              setStreet(next.street);
              setBlockNumber(next.blockNumber);
              setArea(next.area || '');
              setLandmark(next.landmark || '');
              setPostalCode(next.postalCode || '');
            }}
          />
        </div>

        {/* Primary branch checkbox */}
        {showPrimaryCheckbox && (
          <div className="pt-1">
            <label className="flex items-center gap-2 cursor-pointer text-xs text-slate-300 select-none">
              <input
                type="checkbox"
                checked={isPrimary}
                disabled={isPrimaryDisabled}
                onChange={(e) => setIsPrimary(e.target.checked)}
                className={`rounded border-white/20 ${
                  isIndigo ? 'text-indigo-600' : 'text-[#714b67]'
                } focus:ring-0`}
              />
              <span>Mark as primary branch</span>
              {isPrimaryDisabled && (
                <span className="text-[10px] text-slate-500">(First branch is default primary)</span>
              )}
            </label>
          </div>
        )}

        {/* Limit Banner if limit is reached */}
        {isLimitReached && (
          <div className="text-[11px] text-amber-400 bg-amber-500/10 border border-amber-500/20 rounded-md p-3 space-y-1">
            <div className="font-bold flex items-center gap-1.5">
              <Sparkles className="w-3.5 h-3.5" />
              <span>Branch Limit Reached</span>
            </div>
            <p className="text-slate-300">
              {limitBannerMessage ||
                limitTooltip ||
                'Your organization has reached the maximum branch limit for its current subscription tier. Upgrade your plan to add additional branches.'}
            </p>
          </div>
        )}

        {/* Actions */}
        <div className="flex flex-col sm:flex-row items-center justify-end gap-3 pt-3 border-t border-white/10">
          {onCancel && (
            <Button
              type="button"
              variant="ghost"
              size="sm"
              onClick={onCancel}
              className="w-full sm:w-auto h-8 px-3 text-xs text-slate-400 hover:text-white"
            >
              Cancel
            </Button>
          )}

          {secondarySubmitLabel && onSecondarySubmit && (
            <Button
              type="button"
              variant="outline"
              size="sm"
              onClick={handleSecondarySubmit}
              disabled={isSubmitting || isLimitReached}
              className="w-full sm:w-auto h-8 px-3 text-xs font-semibold rounded-md border-white/10 bg-white/5 hover:bg-white/10 text-white disabled:opacity-50 disabled:cursor-not-allowed cursor-pointer gap-1.5"
              title={isLimitReached ? limitTooltip : undefined}
            >
              {isSubmitting ? <Spinner size="sm" /> : <Plus className="w-3 h-3" />}
              <span>{secondarySubmitLabel}</span>
            </Button>
          )}

          <Button
            type="submit"
            size="sm"
            disabled={isSubmitting || !name.trim() || isLimitReached}
            className={`w-full sm:w-auto h-8 px-4 text-xs font-bold rounded-md disabled:opacity-50 disabled:cursor-not-allowed cursor-pointer gap-1.5 ${brandAccentBg}`}
            title={isLimitReached ? limitTooltip : undefined}
          >
            {isSubmitting ? (
              <Spinner size="sm" />
            ) : mode === 'edit' ? (
              <Save className="w-3 h-3" />
            ) : (
              <Plus className="w-3 h-3" />
            )}
            <span>{isSubmitting ? defaultSubmittingText : defaultSubmitText}</span>
          </Button>
        </div>
      </form>

      {/* Phone Verification Modal */}
      {isPhoneVerifyModalOpen && (
        <OtpVerificationModal
          isOpen={isPhoneVerifyModalOpen}
          phone={formatPhoneE164(phoneDigits) || phoneDigits}
          title="Verify Branch Phone"
          subtitle={`We sent a 6-digit SMS verification code to verify ${name || 'branch'}'s contact phone.`}
          onClose={() => setIsPhoneVerifyModalOpen(false)}
          onSuccess={() => {
            setPhoneVerified(true);
            setIsPhoneVerifyModalOpen(false);
          }}
          onVerifyOverride={handleVerifyOtp}
          onResendOverride={handleResendOtp}
        />
      )}
    </>
  );
};

export default BranchForm;
